### PR TITLE
Expand autodiscovery to autotest/discover*.rb

### PR DESCRIPTION
**Pull request by terceiro**
This allows projects to provide multiple auto discovery files for better
organization

### CODE REVIEW

**Comment by zenspider** [comment]
I like this, but I'm going to merge it to seattlerb/minitest-autotest, which is where current autotest development is currently happening. I haven't decided if I'm going to merge the code back here or kill it here.

**Comment by zenspider** [comment]
aaand I lied. The rewrite of autotest in minitest-autotest got rid of the plugin system entirely (because it _only_ supports minitest and rails vs ruby vs whatever-other-setup can be handled via a `.autotest` file. I didn't have a compelling reason for the discovery / plugin mechanism. What are you using it for?

**Comment by terceiro** [comment]
I'm using it to use autotest with rspec

**Comment by terceiro** [comment]
err, not exactly: the issue is I was trying to use autotest with rspec's autotest discovery, but for this to work on debian (with debian packages) I had to move rspec's autotest/discover.rb to autotest/disover_rspec.rb: since in debian we install packages to a shared $LOAD_PATH no 2 packages can provide autotest/discover.rb)

**Comment by zenspider** [comment]
I'm pretty certain that I'm dropping support for rspec. I can merge this in blindly and do a one-time release to get it out there, but at some point I'm going to have to shelve autotest in zentest.

Thoughts?

**Comment by terceiro** [comment]
It would be nice if you could do that release, thanks.

When you remove autotest from zentest, maybe I will eIt's a pitty that you will drop support for anything other than minitest because AFAICT autotest just works with rspec for me, but that is totally your call.

**Comment by zenspider** [comment]
OK. I'll try to get this out soon. Closing.

**Pull request closed without merging**
